namespace RxBlazorV2.CoreTests.TestFixtures;

public partial class CommandFilterTestComponent
{
    /// <summary>
    /// What the generator emits for a razor that references a command and
    /// nothing else: the command's own qualified name. Hand-written here for
    /// the same reason the other fixtures hand-write theirs — the test
    /// project does not run the generator.
    /// </summary>
    protected override string[] Filter()
    {
        return [
            "Model.AsyncCommandWithParam"
        ];
    }

    /// <summary>
    /// Sets up Observable subscription with filtering.
    /// This is normally generated by ComponentCodeGenerator.
    /// </summary>
    protected override void InitializeGeneratedCode()
    {
        var filter = Filter();
        Subscriptions.Add(Model.Observable
            .Where(props => props.Intersect(filter).Any())
            .Chunk(TimeSpan.FromMilliseconds(100))
            .Subscribe(_ =>
            {
                InvokeAsync(StateHasChanged);
            }));
    }
}
