using R3;

namespace RxBlazorV2.CoreTests.TestFixtures;

public partial class RenderCountTrackingComponent
{
    /// <summary>
    /// Manually specified filter for test - only includes Counter (used in razor markup).
    /// Name is NOT in filter to test that changing it doesn't trigger re-render.
    /// </summary>
    protected override string[] Filter()
    {
        return [
            "Model.Counter"
        ];
    }

    /// <summary>
    /// Sets up Observable subscription with filtering.
    /// This is normally generated by ComponentCodeGenerator.
    /// </summary>
    protected override void InitializeGeneratedCode()
    {
        // Subscribe to model changes - respects Filter() method
        var filter = Filter();
        if (filter.Length == 0)
        {
            // No filter - observe all property changes
            Subscriptions.Add(Model.Observable
                .Chunk(TimeSpan.FromMilliseconds(100))
                .Subscribe(chunks =>
                {
                    var props = chunks.SelectMany(c => c).ToArray();
                    InvokeAsync(() => StateHasChanged());
                }));
        }
        else
        {
            // Filter - only observe specific properties
            Subscriptions.Add(Model.Observable
                .Where(props => props.Intersect(filter).Any())
                .Chunk(TimeSpan.FromMilliseconds(100))
                .Subscribe(chunks =>
                {
                    var props = chunks.SelectMany(c => c).ToArray();
                    InvokeAsync(() => StateHasChanged());
                }));
        }
    }
}
